USE sakila;

-- SHOW CREATE
-- -- PROCEDURE
SHOW CREATE PROCEDURE record_count;
-- -- FUNCTION
SHOW CREATE FUNCTION pay_check;
-- -- TRIGGER
SHOW CREATE TRIGGER City_AD;
-- -- EVENT
SHOW CREATE EVENT e_store_ts;

-- SHOW STATUS
-- -- PROCEDURE
SHOW PROCEDURE STATUS;
SHOW PROCEDURE STATUS LIKE 'film%';
-- -- FUNCTION
SHOW FUNCTION STATUS;
-- -- TRIGGERS
SHOW TRIGGERS;
SHOW TRIGGERS LIKE 'City%';
-- -- EVENTS
SHOW EVENTS;

-- INFORMATION_SCHEMA
-- -- ROUTINES
SELECT *
FROM INFORMATION_SCHEMA.ROUTINES;
SELECT
  routine_name,
  routine_schema,
  routine_type,
  definer
FROM INFORMATION_SCHEMA.ROUTINES
WHERE routine_name LIKE 'film%';
-- -- TRIGGERS
SELECT *
FROM INFORMATION_SCHEMA.TRIGGERS;
-- -- EVENTS
SELECT *
FROM INFORMATION_SCHEMA.EVENTS;

-- DROP
-- -- TRIGGER
DROP TRIGGER IF EXISTS City_AD;
-- -- EVENT
DROP EVENT IF EXISTS e_store_ts;


