SHOW DATABASES ;
-- SHOW CREATE TABLE
SHOW CREATE TABLE CITY ;
SHOW TABLES ;
SHOW TABLES FROM SAKILA ;
SHOW OPEN TABLES ;
-- SHOW COLUMS
-- DESCRIBE
-- DESC
SHOW COLUMNS FROM CITY;
DESC CITY ;
SHOW FULL COLUMNS FROM CITY;
-- SHOW INDEX
SHOW INDEX FROM CITY;
SHOW CHARACTER SET ;
SHOW COLLATION ;
SHOW PROCESSLIST ;
SHOW TABLE STATUS ;
SHOW PLUGINS ;
-- GRANT
SHOW GRANTS ;
SHOW GRANTS FOR 'shawnyan'@'%';